Created translation for signup
ita-social-projects/SpaceToStudy-Client pull request #1329
Opened 2023-10-18 13:01 UTC by dmtrth25

**Added translation for signup.json:**

<img width="1018" alt="image" src="https://github.com/ita-social-projects/SpaceToStudy-Client/assets/56305508/652aa2da-399c-4e38-98f3-836f17f9cdcd">

**Resolved issue: #1323**

2023-10-18 13:03 UTC, MariaAfonina approved these changes

2023-10-18 13:34 UTC, abalanovsky approved these changes

2023-10-19 07:29 UTC, Tolik170 approved these changes

2023-10-19 12:47 UTC, TSlashDreamy approved these changes

2023-10-20 11:07 UTC, maarekua requested changes

2023-10-20 11:07 UTC, maarekua commented on src/constants/translations/ua/signup.json
> +  "and": "та",
Looks like a common translation.

2023-10-20 11:07 UTC, maarekua commented on src/constants/translations/ua/signup.json
> +  "continue": "або продовжити",
same

2023-10-20 11:07 UTC, maarekua commented on src/constants/translations/ua/signup.json
> +  "joinUs": "Увійти!",
same

2023-10-20 11:14 UTC, maarekua approved these changes

2023-10-20 12:53 UTC, merged