change registration layout(remove input jump on error)
ita-social-projects/SpaceToStudy-Client pull request #152
Opened 2022-07-22 07:43 UTC by RestingState

2022-07-22 07:50 UTC, rostyslaw27 requested changes

2022-07-22 07:50 UTC, rostyslaw27 commented on src/containers/guest-home-page/signup-form/SignupForm.js
> +        type={ (showConfirmPassword ? 'text' : 'confirmPassword') }
there is no type like confirmPassword. Change to password

2022-07-23 10:46 UTC, rostyslaw27 requested changes

2022-07-23 10:46 UTC, rostyslaw27 commented on src/containers/guest-home-page/signup-form/signup-form.style.js
> +    whiteSpace: 'nowrap'
delete this unused style

2022-07-24 12:16 UTC, RestingState commented on src/containers/guest-home-page/signup-form/signup-form.style.js
> +    whiteSpace: 'nowrap'
Deleted

2022-07-28 07:28 UTC, rostyslaw27 approved these changes

2022-07-29 08:08 UTC, closed without merging