Added drawer filter for my resources toolbar on mobile and tablet
ita-social-projects/SpaceToStudy-Client pull request #1523
Opened 2023-12-20 10:58 UTC by Tolik170

2023-12-21 14:01 UTC, abalanovsky approved these changes

2023-12-21 16:51 UTC, OlyaKorchan approved these changes

2023-12-25 18:36 UTC, dmtrth25 approved these changes

2024-01-15 09:50 UTC, maarekua requested changes

2024-01-16 12:02 UTC, Tolik170 commented on src/components/filter-selector/FilterSelector.tsx
> +    const initialNames = filteredItems
yeah, this useEffect is also using for options selection, so I changed the naming of that variable to **"filteredNames"**

2024-01-16 12:04 UTC, Tolik170 commented on tests/unit/containers/my-resources/AddResourceWithInput.spec.jsx
> +    sort: { order: 'desc', orderBy: 'updatedAt' }
Used SortEnum for **'desc'** and **'asc'** values

2024-01-18 11:18 UTC, Mav-Ivan approved these changes

2024-01-26 11:56 UTC, maarekua approved these changes

2024-01-26 11:59 UTC, merged