Implemented saving cooperation section as a copy
ita-social-projects/SpaceToStudy-Client pull request #1731
Opened 2024-04-03 19:22 UTC by Mav-Ivan

https://github.com/ita-social-projects/SpaceToStudy-Client/assets/110425368/be60c264-34a1-4be1-851a-87d65577c650

2024-04-04 08:54 UTC, maarekua requested changes

2024-04-04 08:54 UTC, maarekua commented on src/containers/cooperation-details/cooperation-activities/CooperationActivities.tsx
> +  cooperationId: string | undefined
cooperationIs?: string

2024-04-04 10:07 UTC, Tolik170 commented on src/containers/cooperation-details/cooperation-activities/CooperationActivities.tsx
> +import { useSnackBarContext } from '~/context/snackbar-context'
organize imports

2024-04-04 10:59 UTC, Mav-Ivan commented on src/containers/cooperation-details/cooperation-activities/CooperationActivities.tsx
> +  cooperationId: string | undefined
fixed

2024-04-04 11:29 UTC, abalanovsky approved these changes

2024-04-04 15:46 UTC, Tolik170 approved these changes

2024-04-06 16:52 UTC, dmtrth25 approved these changes

2024-04-08 19:06 UTC, maarekua approved these changes

2024-04-09 13:16 UTC, merged