Added AccordionWithImage to storybook
ita-social-projects/SpaceToStudy-Client pull request #204
Opened 2022-08-09 13:50 UTC by Tolik170

Result:

![image](https://user-images.githubusercontent.com/63456632/183665941-19c8baf6-40b2-4535-96aa-36462dea8fe3.png)

2022-08-09 15:45 UTC, rostyslaw27 requested changes

2022-08-09 15:45 UTC, rostyslaw27 commented on src/stories/AccordionWithImage.stories.js
> +export const Desktop = Template.bind({})
better name it Default, not desktop

2022-08-09 18:55 UTC, Tolik170 commented on src/stories/AccordionWithImage.stories.js
> +export const Desktop = Template.bind({})
fixed

2022-08-09 21:37 UTC, rostyslaw27 approved these changes

2022-08-10 09:53 UTC, maarekua approved these changes

2022-08-10 17:44 UTC, rostyslaw27 approved these changes

2022-08-10 17:44 UTC, merged