Redesign categories and subjects
ita-social-projects/SpaceToStudy-Client pull request #2040
Opened 2024-07-02 16:46 UTC by YaroslavChuiko

- [x] Redesign categories and subjects
- [x] Show proper icons and colors

The MUI library doesn't include a delete icon used in the Figma design, so I pick similar from the MUI.
Also in the Figma design edit button has an unstandard color, I am using one of the default buttonn colors that we have in our project

![image](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/32570823/38cacaf0-b17c-4e63-9a03-0ce2c0e850c3)

[screen-capture (8).webm](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/32570823/99d614e4-620d-48f2-9d9b-aa1c0131ca86)

2024-07-03 12:08 UTC, docia requested changes
the current code looks great to me. I have the same Sonar failed conditions in PR  #2045

2024-07-03 13:17 UTC, Mike-Popovych approved these changes

2024-07-03 15:00 UTC, abalanovsky approved these changes

2024-07-03 22:54 UTC, Olenka-Hryk approved these changes

2024-07-04 10:15 UTC, YaroslavLys approved these changes

2024-07-05 10:48 UTC, docia approved these changes

2024-07-05 10:48 UTC, merged