Add feature student profile items
ita-social-projects/SpaceToStudy-Client pull request #2165
Opened 2024-07-24 17:57 UTC by dudchakk

- [x] add conditional rendering based on user role (student/tutor)
- [x] implement categories profile item
- [x] implement location profile item
- [x] implement request profile item
- [x] expand CompleteProfileBlock tests

![Screenshot 2024-07-24 203759](https://github.com/user-attachments/assets/b1763e0c-6fd5-4c2b-839b-c0ef0938f958)

tests:
![Screenshot 2024-07-24 204028](https://github.com/user-attachments/assets/07c7229f-715e-409b-a434-1dbd90cf9d53)

2024-07-25 10:38 UTC, Olenka-Hryk commented on src/components/complete-profile/CompleteProfileBlock.tsx
>      [profileItems, checkProfileData]
Could you please fix this warning about the missing dependency?

2024-07-25 10:44 UTC, Olenka-Hryk requested changes

2024-07-25 10:44 UTC, Olenka-Hryk commented on src/components/complete-profile/CompleteProfileBlock.tsx
<img width="796" alt="Screenshot 2024-07-25 at 13 41 31" src="https://github.com/user-attachments/assets/a00870f1-e7eb-4581-b54c-5fe03e6c0fef">

2024-07-25 20:42 UTC, Olenka-Hryk approved these changes

2024-07-26 06:25 UTC, YaroslavChuiko approved these changes

2024-07-26 10:31 UTC, abalanovsky approved these changes

2024-07-28 12:18 UTC, docia approved these changes

2024-07-29 10:43 UTC, Mike-Popovych approved these changes

2024-08-05 14:38 UTC, merged