Fix bug with disabled "Save changes" button
ita-social-projects/SpaceToStudy-Client pull request #2170
Opened 2024-07-25 10:31 UTC by BohdanMylyi

The user can click on Save changes button and save category even with empty subjects

https://github.com/user-attachments/assets/b09ef390-cc8d-4827-9f77-fad656ace63c

https://github.com/user-attachments/assets/6bc87edd-e174-4c9c-8221-3d262b02e20d

2024-07-25 11:11 UTC, Olenka-Hryk requested changes

2024-07-25 11:11 UTC, Olenka-Hryk commented on package-lock.json
Could you revert the changes in `package-lock.json`? Also, why did you update `@typescript-eslint/eslint-plugin` in this PR? Is it necessary to solve this issue? I think such updates should be in a separate PR.

2024-07-25 11:13 UTC, BohdanMylyi commented on package-lock.json
> Could you revert the changes in `package-lock.json`? Also, why did you update `@typescript-eslint/eslint-plugin` in this PR? Is it necessary to solve this issue? I think such updates should be in a separate PR.

ok, I'll change it

2024-07-25 11:15 UTC, Olenka-Hryk commented on package-lock.json
Thanks 👍🏻

2024-07-25 11:17 UTC, BohdanMylyi commented on package-lock.json
> Thanks 👍🏻

i've a question, is it ok, if not all tests are passed?
because functional is right, but tests failed

2024-07-25 14:51 UTC, Olenka-Hryk commented on package-lock.json
No, it is not acceptable for **CI/tests** to fail. You can't merge a PR if there are failed tests. Several issues could be causing the failures. In your case, you changed the `AddProfessionalCategoryModal.tsx` component, which is why tests for this component are failing in CI.

I haven't investigated thoroughly, but I noticed that you modified the `const userMainSubjectTemplate` in `AddCourseTemplateModal.tsx` - `{ _id: '', name: '', appearance: { color: '', icon: '' } }` [here](src/containers/cooperation-details/add-course-modal-modal/AddCourseTemplateModal.tsx). However, the tests are still mocking it as: 
<img width="510" alt="Screenshot 2024-07-25 at 17 45 01" src="https://github.com/user-attachments/assets/afb69ab7-089a-4196-bcbe-ae5ee51758f8">

This discrepancy might be one reason why the tests are failing. You should identify the main problem and update your tests accordingly. Tests written before the component logic change may no longer work as expected.

2024-07-30 08:39 UTC, BohdanMylyi commented
a lot of unnecessary changes

2024-07-30 08:39 UTC, closed without merging