Rewrote ProfileContainerMobile to tsx
ita-social-projects/SpaceToStudy-Client pull request #2220
Opened 2024-07-26 13:20 UTC by Pasichnichenkoilya

2024-07-26 14:30 UTC, Olenka-Hryk approved these changes

2024-07-27 12:52 UTC, YaroslavChuiko approved these changes

2024-07-28 15:40 UTC, docia approved these changes

2024-07-29 20:22 UTC, PavloDolia requested changes

2024-07-29 20:22 UTC, PavloDolia commented on src/containers/user-profile/profile-info/ProfileContainerMobile.tsx
> +  doneItems: number
doneItems is not a number, it's an array of objects { title: string, description: string }

2024-07-30 11:29 UTC, PavloDolia approved these changes

2024-08-01 10:10 UTC, Mike-Popovych approved these changes

2024-08-02 10:46 UTC, merged