Fix incorrect translation of description
ita-social-projects/SpaceToStudy-Client pull request #2228
Opened 2024-07-27 10:25 UTC by Renatavl

2024-07-27 13:00 UTC, YaroslavChuiko approved these changes

2024-07-28 16:01 UTC, docia commented
when being on your branch, I noticed that other translations broke with the changes in the current PR. regardless logging as a tutor or student. 
please take a look at banners when you return to the Home page, or click on Categoreis, Subjects, and All offers. 

<img width="1469" alt="Screenshot 2024-07-28 at 18 54 34" src="https://github.com/user-attachments/assets/f12551ac-2850-44e9-a685-74ad9adfb3f5">
<img width="1468" alt="Screenshot 2024-07-28 at 18 54 51" src="https://github.com/user-attachments/assets/adf2a651-ba6a-4f35-890b-83f7670252dc">

2024-07-28 16:04 UTC, docia requested changes
when being on your branch, I noticed that other translations broke with the changes in the current PR. regardless logging as a tutor or student.
please take a look at banners when you return to the Home page, or click on Categoreis, Subjects, and All offers and ensure the banner translation is also correct when using en and uk interface. 
<img width="1469" alt="Screenshot 2024-07-28 at 18 54 34" src="https://github.com/user-attachments/assets/4f4896f0-5452-477e-8adf-c980d70938c7">
<img width="1468" alt="Screenshot 2024-07-28 at 18 54 51" src="https://github.com/user-attachments/assets/8e71c9ad-f0b5-42ba-bac4-63cf3fb46e26">

2024-08-07 22:16 UTC, Renatavl commented
@docia 
Done according to comment

2024-08-28 07:44 UTC, abalanovsky approved these changes

2024-09-03 18:50 UTC, docia approved these changes

2024-09-12 20:51 UTC, merged