Rewrite LoginForm to tsx format and fix the sonar issues
ita-social-projects/SpaceToStudy-Client pull request #2236
Opened 2024-07-28 11:01 UTC by BohdanMylyi

Rewrite LoginForm to tsx format and fix the sonar issues

2024-07-28 11:19 UTC, Olenka-Hryk requested changes

2024-07-28 11:19 UTC, Olenka-Hryk commented on src/containers/guest-home-page/login-form/LoginForm.tsx
Can you replace `useSelector` import from `react-redux` with typed hooks to resolve GitHub Actions warning?
<img width="964" alt="Screenshot 2024-07-28 at 14 18 40" src="https://github.com/user-attachments/assets/415839a2-25d4-4011-ba45-a75f60afbfd3">

2024-07-28 11:34 UTC, BohdanMylyi commented on src/containers/guest-home-page/login-form/LoginForm.tsx
yes, no problem

2024-07-28 12:28 UTC, BohdanMylyi commented on src/containers/guest-home-page/login-form/LoginForm.tsx
> Can you replace `useSelector` import from `react-redux` with typed hooks to resolve GitHub Actions warning?
I tried to replace with typed hooks, but for this we still need to export useSelector, and we get some kind of infinite circle, and EsLint asks to replace anyway.

2024-07-28 16:27 UTC, docia approved these changes

2024-07-29 09:15 UTC, Olenka-Hryk commented on src/containers/guest-home-page/login-form/LoginForm.tsx
> +  const handleCheckboxChange = (
Is it necessary to create a new function `handleCheckboxChange` instead of using `handleChange`?

2024-07-29 15:02 UTC, Olenka-Hryk commented on sonar-project.properties
Can you revert these changes? Because they are not from your PR. They are in PR #2232

2024-07-29 15:02 UTC, Olenka-Hryk approved these changes

2024-08-01 10:29 UTC, Mike-Popovych approved these changes

2024-08-02 10:52 UTC, merged