Rewrite GoogleLogin to tsx format and fix the sonar issues
ita-social-projects/SpaceToStudy-Client pull request #2243
Opened 2024-07-29 08:54 UTC by BohdanMylyi

Rewrite GoogleLogin to tsx format and fix the sonar issues

2024-07-29 09:54 UTC, Olenka-Hryk requested changes

2024-07-29 09:54 UTC, Olenka-Hryk commented on tsconfig.json
> +
Delete the unnecessary space in this file!

2024-07-29 10:41 UTC, abalanovsky approved these changes

2024-07-29 10:42 UTC, Olenka-Hryk approved these changes

2024-07-31 10:58 UTC, docia approved these changes

2024-08-01 10:33 UTC, Mike-Popovych approved these changes

2024-08-02 10:53 UTC, merged