Prevented Description Text from Exceeding Container Bounds
ita-social-projects/SpaceToStudy-Client pull request #2256
Opened 2024-07-30 18:07 UTC by YulichkaR

Before:
![image](https://github.com/user-attachments/assets/71fc15dc-2356-4775-9067-ea6725968bbe)

After:
![image](https://github.com/user-attachments/assets/6548631d-5de6-4041-8d89-f025cd13d12e)

2024-07-31 07:56 UTC, YaroslavChuiko approved these changes

2024-07-31 13:51 UTC, dudchakk requested changes
Hi! Looks like you set the container width to be stable, 1000px. This code probably wouldn’t work on other devices like phones or laptops. Please try to fix it

2024-08-06 17:52 UTC, Mike-Popovych approved these changes

2024-08-06 18:07 UTC, abalanovsky approved these changes

2024-08-06 19:55 UTC, merged