Increased test coverafe for CreateOrEditLesson.tsx
ita-social-projects/SpaceToStudy-Client pull request #2272
Opened 2024-08-03 15:13 UTC by PavloDolia

Increased test coverafe for CreateOrEditLesson.tsx

2024-08-06 15:14 UTC, Olenka-Hryk approved these changes
Good job 👍🏻

2024-08-06 18:12 UTC, abalanovsky requested changes

2024-08-06 18:12 UTC, abalanovsky commented on tests/unit/pages/create-or-edit-lesson/CreateOrEditLesson.spec.jsx
> +    const attachment = await screen.findByText('test.pdf')
maybe better use ``fileName``?

2024-08-07 14:55 UTC, YaroslavLys approved these changes

2024-08-08 06:58 UTC, PavloDolia commented on tests/unit/pages/create-or-edit-lesson/CreateOrEditLesson.spec.jsx
> +    const attachment = await screen.findByText('test.pdf')
good idea, removed these magic strings

2024-08-08 12:43 UTC, abalanovsky approved these changes

2024-08-08 17:17 UTC, merged