Fix coop details buttons
ita-social-projects/SpaceToStudy-Client pull request #2315
Opened 2024-08-09 11:39 UTC by BohdanMylyi

Result:
![image](https://github.com/user-attachments/assets/4eedb1e0-9cbe-4ef3-99ee-6a3cab1c1048)

2024-08-09 11:57 UTC, Pasichnichenkoilya approved these changes

2024-08-11 18:25 UTC, dudchakk approved these changes

2024-08-12 09:13 UTC, abalanovsky commented on tests/unit/hooks/use-load-more.spec.jsx
> +  it('should open modal window', async () => {
Why use-load-more test is here in this pull request?

2024-08-14 08:36 UTC, docia requested changes
the code is good. Artem's question is also relevant for me.

2024-08-14 10:42 UTC, merged