Add functionality to bookmark icons
ita-social-projects/SpaceToStudy-Client pull request #2325
Opened 2024-08-13 07:13 UTC by PavloDolia

1. Added functionality to bookmarks icons on the FindOffers page.
2. Added the bookmarks icon to the header. The icon has no functionality.

2024-08-19 09:03 UTC, YaroslavChuiko requested changes

2024-08-19 09:03 UTC, YaroslavChuiko commented on src/components/app-button/AppButton.tsx
We shouldn't change AppButton component as part of this PR, because AppButton is used in many places all over the project and you need to ensure that it works properly in all places after changes. If you want to enhance AppButton it is better to create separate PR

2024-08-19 11:10 UTC, YaroslavChuiko approved these changes

2024-08-25 13:26 UTC, Mike-Popovych approved these changes

2024-08-27 18:00 UTC, docia approved these changes

2024-08-27 19:08 UTC, Olenka-Hryk approved these changes

2024-08-27 19:38 UTC, merged