Corrected date translation in all possible places on the website
ita-social-projects/SpaceToStudy-Client pull request #2344
Opened 2024-08-14 21:53 UTC by Renatavl

Changed logic of formatting dates by adding date translation 

![image_2024-08-15_00-05-19](https://github.com/user-attachments/assets/d787bcb5-8e7c-4296-85c7-bec8fbb81e53)

![image_2024-08-15_00-05-42](https://github.com/user-attachments/assets/4a696add-7590-42f9-b64a-84f9bdc92024)

2024-08-15 06:09 UTC, YaroslavChuiko requested changes

2024-08-15 06:09 UTC, YaroslavChuiko commented on src/utils/helper-functions.tsx
> +  const { i18n } = useTranslation()
We can't ignore this rule, you need to fix that

![image](https://github.com/user-attachments/assets/1b5ac9d2-5d33-48f8-85be-68a37aba9d6f)

[React documentation](https://react.dev/warnings/invalid-hook-call-warning#breaking-rules-of-hooks)

2024-08-15 08:53 UTC, dudchakk approved these changes

2024-08-29 15:28 UTC, docia approved these changes

2024-08-29 15:38 UTC, ut5tw approved these changes

2024-08-29 16:33 UTC, YaroslavChuiko approved these changes

2024-08-29 17:04 UTC, merged