Added bookmark icon in Offer Cards within OfferCarousel
ita-social-projects/SpaceToStudy-Client pull request #2349
Opened 2024-08-15 13:43 UTC by Renatavl

![image](https://github.com/user-attachments/assets/873146c5-df95-425a-8861-54259bd6344d)

2024-08-15 14:17 UTC, BohdanMylyi requested changes

2024-08-15 14:17 UTC, BohdanMylyi commented on src/containers/offer-details/offer-carousel/OfferCarousel.tsx
> +      console.log(id)
the same as we discussed on meeting(on my PR), try to replace it by returning "null"

2024-08-19 08:16 UTC, dudchakk approved these changes

2024-08-22 11:52 UTC, YaroslavChuiko approved these changes

2024-08-26 07:45 UTC, Pasichnichenkoilya approved these changes

2024-10-02 08:50 UTC, Mav-Ivan commented
improve test coverage
![image](https://github.com/user-attachments/assets/8b8474ea-0801-41e2-9807-77c7c6418034)

2024-10-07 12:31 UTC, PavloDolia approved these changes

2024-10-15 15:57 UTC, BohdanMylyi approved these changes

2024-10-15 15:58 UTC, ut5tw commented
Please increase coverage

2024-10-19 19:27 UTC, merged