Bugfix/2314/change offers to requests
ita-social-projects/SpaceToStudy-Client pull request #2459
Opened 2024-09-05 17:48 UTC by Renatavl

![image](https://github.com/user-attachments/assets/1358e171-6b00-4bbf-9ea6-aa7796b19199)

![image](https://github.com/user-attachments/assets/7fa425f8-a8d1-4c94-bea0-7f923b5b68cd)

2024-09-05 18:03 UTC, docia reviewed
<img width="982" alt="Screenshot 2024-09-05 at 21 00 38" src="https://github.com/user-attachments/assets/26e7b493-3288-4b39-b6dd-5014cacc8f04">
I believe 'Edit offer' should also be changed to 'Edit request' here. If we are logged in as a Student.

2024-09-05 20:45 UTC, dudchakk commented on src/utils/helper-functions.tsx
These changes probably refer to your “change translation of dates” PR, can you remove them from this PR?

2024-09-12 20:26 UTC, Renatavl commented on src/utils/helper-functions.tsx
Done

2024-09-12 20:28 UTC, Renatavl commented
> I believe 'Edit offer' should also be changed to 'Edit request' here. If we are logged in as a Student.

Done
![image](https://github.com/user-attachments/assets/385ff014-1f7a-4bf0-8dd8-c1c7f8fbf1da)

2024-09-15 10:38 UTC, PavloDolia reviewed
We also need to change breadcrumbs and headings (Offer details and About Offer) at the Offer details page.
<img width="1440" alt="Screenshot 2024-09-15 at 13 37 59" src="https://github.com/user-attachments/assets/2cf743a2-3d63-46a1-a8e1-94407befdab3">

2024-09-25 12:40 UTC, dudchakk commented on src/constants/translations/en/button.json
you've used 'student' and 'tutor' options everywhere else, maybe do the same here instead of 'viewMyOffers' and 'viewMyRequests'

2024-09-25 12:41 UTC, dudchakk commented on src/constants/translations/uk/button.json
same with 'student' and 'tutor'

2024-09-25 12:56 UTC, dudchakk requested changes
we have a problem when clicking on 'request details':

https://github.com/user-attachments/assets/b044c980-700f-4f1c-9bcd-beb6c2304f5d

either fix this page in this PR or create a new issue)

2024-10-22 21:32 UTC, Renatavl commented
> We also need to change breadcrumbs and headings (Offer details and About Offer) at the Offer details page. <img alt="Screenshot 2024-09-15 at 13 37 59" width="1440" src="https://private-user-images.githubusercontent.com/123400767/367575558-2cf743a2-3d63-46a1-a8e1-94407befdab3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MzI4OTgsIm5iZiI6MTcyOTYzMjU5OCwicGF0aCI6Ii8xMjM0MDA3NjcvMzY3NTc1NTU4LTJjZjc0M2EyLTNkNjMtNDZhMS1hOGUxLTk0NDA3YmVmZGFiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQyMTI5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTRlNTc3NzFmNGVmMGFmMzE0ZWYwYzA5YjM2YTJlYmZlNTliMjdjNzYwOTZlODJlNTVmNTQ0YWFmZTQwNjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CQfT_elF_LuuFxLT-Zf0UnRvC-JbdnxzYTD4Q4I3L1w">

I will add a new task for this issue

2024-10-23 07:13 UTC, YaroslavChuiko approved these changes

2024-10-23 10:26 UTC, PavloDolia approved these changes

2024-10-24 08:35 UTC, ut5tw approved these changes

2024-10-24 11:29 UTC, dudchakk approved these changes

2024-10-24 11:39 UTC, merged