Fix cooperation details visual bugs
ita-social-projects/SpaceToStudy-Client pull request #2513
Opened 2024-09-12 15:41 UTC by BohdanMylyi

Before changes:
![s1](https://github.com/user-attachments/assets/8d91785f-fc4a-4ab6-87d6-682094e0f7a4)
![s2](https://github.com/user-attachments/assets/69ed636f-eb1f-44d8-a27e-2cfcbc550b34)

Actual result:
![image](https://github.com/user-attachments/assets/c8dbbf53-aeea-4124-b664-2a6af33d8949)

2024-09-12 16:48 UTC, YaroslavChuiko approved these changes

2024-09-14 09:02 UTC, PavloDolia requested changes
The cooperation details tab doesn't match the figma design.
The distance between a category and a category icon should be 8px (it's 14px now).
The distance between a category and a subject should be 16px (it's 4px now).
<img width="353" alt="Screenshot 2024-09-14 at 11 59 56" src="https://github.com/user-attachments/assets/61dadf1b-4f02-43a8-a328-bb04aa68c665">
<img width="369" alt="Screenshot 2024-09-14 at 11 59 46" src="https://github.com/user-attachments/assets/50f603b6-e9f7-4904-94a0-281ac0b97998">

https://github.com/user-attachments/assets/4d6103bd-dad7-4ea4-bf39-188579d995fc

2024-09-14 11:20 UTC, PavloDolia approved these changes
now it looks as intended 👍

2024-09-14 14:20 UTC, OliaHrytsak approved these changes

2024-09-15 13:33 UTC, merged