Your schedule
ita-social-projects/SpaceToStudy-Client pull request #2538
Opened 2024-09-19 22:26 UTC by Renatavl

![image](https://github.com/user-attachments/assets/0ef0f958-974e-4806-8190-3130c31e7e25)

2024-09-21 10:37 UTC, ut5tw requested changes
- Consider adding some test coverage
- Ensure the block is responsive:

![image](https://github.com/user-attachments/assets/649a3774-c30f-4f4e-9f41-78c69929b76c)

2024-09-21 10:37 UTC, ut5tw commented on src/components/tutor-schedule/TutorSchedule.tsx
> +          <Box key={index} sx={styles.card_container}>
try to avoid using `index` as a `key`

2024-09-21 10:37 UTC, ut5tw commented on src/pages/tutor-home/TutorHome.tsx
> +      <TutorSchedule />
`TutorSchedule` block should be below the  `FindBlock`, according to [figma](https://www.figma.com/design/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=2140-54676&t=hIwawP1kVQcUFyJK-4)

2024-09-21 12:24 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.styles.ts
> +    width: '500px',
try do not use the fixed parameters like width and height because it involves a problems with responsive behavior

2024-09-21 12:26 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.styles.ts
> +    typography: 'h5',
We thy to use one approach in all styling files with reusable enums

![image](https://github.com/user-attachments/assets/0a05d1ed-6ee4-40fe-ba12-36b008ce47cd)

2024-09-21 12:26 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.styles.ts
> +    typography: 'subtitle1',
the same as above

2024-09-21 12:27 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.styles.ts
> +    width: '500px',
the same
Thry to use max-width for example

2024-09-21 12:29 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.styles.ts
> +    typography: 'subtitile2'
use enum, please

2024-09-21 12:29 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.styles.ts
> +      typography: 'h6',
enums

2024-09-21 12:30 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.styles.ts
> +    typography: 'h6',
unum

2024-09-21 12:33 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.tsx
> +import { Avatar, Box, Button, Typography } from '@mui/material'
We already have AvatarIcon, AppButton components
Please, reuse it!

2024-09-21 12:34 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.tsx
> +      <Typography sx={styles.section_title}>Your schedule</Typography>
you can use enum even like that

<Typography variant={TypographyVariantEnum.YOUR VARIANT}>

2024-09-21 12:37 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.styles.ts
> +export const styles = {
ALL styles wariables should be in camelCase, like in add styles files along thr app

2024-09-21 12:38 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.tsx
> +              <Typography>
You can create variable for better readability

2024-09-21 12:39 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.styles.ts
> +    backgroundColor: '#ffff',
don't hardcode

2024-09-21 12:41 UTC, OliaHrytsak commented on src/components/tutor-schedule/TutorSchedule.constants.ts
> +export const items = [
This file is redundant. For tast purpose this mock can be in one file with component

2024-09-22 14:55 UTC, BohdanMylyi commented
also fix sonar issue
![image](https://github.com/user-attachments/assets/1ed9091b-4d94-490d-b4d3-ea7fa23f0766)

2024-09-26 14:32 UTC, BohdanMylyi approved these changes

2024-09-26 15:04 UTC, YaroslavChuiko approved these changes

2024-09-26 15:16 UTC, PavloDolia approved these changes

2024-09-26 15:30 UTC, ut5tw approved these changes

2024-09-26 15:32 UTC, merged