Changed the position of the opening date input
ita-social-projects/SpaceToStudy-Client pull request #2564
Opened 2024-09-30 15:30 UTC by Renatavl

![image](https://github.com/user-attachments/assets/b1a350fb-3ead-4be7-a3e1-10037297d450)

2024-09-30 15:48 UTC, PavloDolia requested changes
the drop-down list with availability options has disappeared
Before:
<img width="1123" alt="before" src="https://github.com/user-attachments/assets/32980d57-d065-4b88-8111-985f63ac98d6">
After:
<img width="1124" alt="after" src="https://github.com/user-attachments/assets/2982c18a-77f8-4dfb-bd4b-415efd3f94b7">

2024-09-30 21:38 UTC, PavloDolia approved these changes

2024-10-01 18:48 UTC, YaroslavChuiko approved these changes

2024-10-01 18:51 UTC, BohdanMylyi approved these changes

2024-10-01 20:22 UTC, ut5tw approved these changes

2024-10-01 22:23 UTC, merged