Display active tab in URL on "My cooperations" and "My offers" pages
ita-social-projects/SpaceToStudy-Client pull request #2630
Opened 2024-10-18 10:06 UTC by YaroslavChuiko

- [x] Active tab on the "My cooperations" and "My offers" pages should be displayed in the URL

2024-10-23 10:24 UTC, PavloDolia approved these changes

2024-10-24 08:34 UTC, ipasic-softserve approved these changes

2024-10-24 11:10 UTC, dudchakk requested changes

2024-10-24 11:10 UTC, dudchakk commented on src/pages/my-cooperations/MyCooperations.tsx
you can move the type definition from this file to one in the 'types' container

2024-10-24 11:10 UTC, dudchakk commented on src/pages/my-offers/MyOffers.tsx
same with type

2024-10-24 11:10 UTC, dudchakk commented on src/pages/my-offers/MyOffers.tsx
add brackets for `if` block for readabitily, unless we have a convention to omit them if the `if` block has only one statement

2024-10-24 13:20 UTC, YaroslavChuiko commented on src/pages/my-cooperations/MyCooperations.tsx
I think we shouldn't move this type definition to a separate file because this type is specific for MyCooperation and is used only in this component

2024-10-24 13:20 UTC, YaroslavChuiko commented on src/pages/my-offers/MyOffers.tsx
I think we shouldn't move this type definition to a separate file because this `type` is specific for MyOffers and is used only in this component

2024-10-28 10:16 UTC, dudchakk commented on src/pages/my-cooperations/MyCooperations.tsx
Okay, I see that this type depends on `tabsInfo`, so we can leave its definition here

2024-10-28 10:17 UTC, dudchakk approved these changes

2024-10-28 10:45 UTC, merged