Fixed header
ita-social-projects/SpaceToStudy-Client pull request #2653
Opened 2024-10-30 13:39 UTC by Mav-Ivan

![image](https://github.com/user-attachments/assets/f88db195-6de8-4c80-a22d-d97299cf59fd)

2024-11-02 20:05 UTC, Renatavl requested changes

2024-11-02 20:05 UTC, Renatavl commented on src/containers/my-cooperations/cooperation-details/CooperationDetails.styles.ts
> +      width: { sm: '100%', md: '100%' },
Please remove `'md: 100%'`, because if you write `'sm: 100%'` it will be applied to all screen sizes (from `sm` to `xl `including `md`)

2024-11-07 10:12 UTC, dudchakk approved these changes
could you rename the PR to something like 'Fixed cooperation heading', because header is another element in our project and this PR is a bit confusing?

2024-11-14 12:51 UTC, Renatavl approved these changes

2024-11-14 18:43 UTC, ut5tw approved these changes

2024-11-20 14:46 UTC, merged