Added Progress Bar for Cooperation
ita-social-projects/SpaceToStudy-Client pull request #2691
Opened 2024-11-13 13:34 UTC by amoutens

2024-11-13 23:39 UTC, Renatavl requested changes

2024-11-13 23:39 UTC, Renatavl commented on src/components/app-progress-bar-line/AppProgressBarLine.styles.ts
> +    marginBottom: { xs: '2px', sm: '24px' }
Replace `"marginBottom"` with `"mb"`, `"marginLeft"` with `"ml"` and so on in all CSS files

2024-11-13 23:39 UTC, Renatavl commented on src/components/app-progress-bar-line/AppProgressBarLine.styles.ts
> +    alignItems: { xs: 'center' },
It's useless to write `{ xs: "center" }`. Please replace it with just `"center"`

2024-11-13 23:39 UTC, Renatavl commented on src/components/app-progress-bar-line/AppProgressBarLine.styles.ts
> +    marginBottom: { xs: '0', sm: '0px' },
Set `mb` to `0` without screen breakpoints

2024-11-13 23:39 UTC, Renatavl commented on src/components/app-progress-bar-line/AppProgressBarLine.tsx
> +import Image from '~/assets/img/cooperation-details/clock.svg'
Maybe it is better to use MUI icons

2024-11-13 23:39 UTC, Renatavl commented on src/components/app-progress-bar-line/AppProgressBarLine.tsx
> +    <Typography color='primary.500' variant='subtitle2'>
1. `"Width"`, `"display"`, `"mb"` and so on move to style files
2. For typography we have specific predefined values. Example: `typography: TypographyVariantEnum.Body1`
3. Do not use hardcoded color codes. Use from palette

2024-11-13 23:39 UTC, Renatavl commented on src/containers/cooperation-details/cooperation-activities-view/CooperationActivitiesView.tsx
> +          userRole={''}
You don't need curly brackets here

2024-11-14 18:50 UTC, ipasic-softserve requested changes

2024-11-14 18:50 UTC, ut5tw commented on src/components/app-progress-bar-line/AppProgressBarLine.tsx
> +        Your progress
You need to translate this into both English and Ukrainian, then use the translated values with `react-i18next`

2024-11-14 18:50 UTC, ut5tw commented on src/components/app-progress-bar-line/AppProgressBarLine.tsx
> +          {`${value}% completed`}
Same here, translation

2024-11-14 18:50 UTC, ut5tw commented on src/components/app-progress-bar-line/AppProgressBarLine.tsx
> +            {`${100 - value}% to complete`}
Translation

2024-11-14 20:06 UTC, ut5tw commented on src/assets/img/cooperation-details/clock.svg
Instead of svg image we use [Material Icons](https://mui.com/material-ui/material-icons/), in this case `AccessTime` would work fine imo

2024-11-14 20:17 UTC, amoutens commented on src/assets/img/cooperation-details/clock.svg
I have already changed svg icon to MUI AccessTime in Refactor: CSS fixing commit

2024-11-14 20:20 UTC, ut5tw commented on src/assets/img/cooperation-details/clock.svg
Then you can just delete the svg file

2024-11-14 20:21 UTC, ut5tw approved these changes

2024-11-19 15:28 UTC, Mav-Ivan commented on src/components/app-progress-bar-line/AppProgressBarLine.tsx
>        : [0, 20, 40, 60, 80, 100]
it`s better to relocate those arrays to the .constants file

2024-11-19 15:29 UTC, Mav-Ivan commented on src/components/app-progress-bar-line/AppProgressBarLine.tsx
> +    <Box width={'100%'}>
relocate this width to the styles file

2024-11-19 20:31 UTC, Renatavl approved these changes

2024-11-24 11:13 UTC, markgol777 approved these changes

2024-11-25 14:04 UTC, merged