Rewrite FilterCell to tsx
ita-social-projects/SpaceToStudy-Client pull request #2744
Opened 2024-11-17 16:46 UTC by ArtemHolikov

rewrote FilterCell to tsx and fixed sonar issues:

![image](https://github.com/user-attachments/assets/34be1a22-741a-4c7f-9ff4-5d2b4f093647)

2024-11-19 15:49 UTC, Mav-Ivan approved these changes

2024-11-28 20:27 UTC, Made1ra requested changes

2024-11-28 20:27 UTC, Made1ra commented on src/components/enhanced-table/filter-row/filter-cell/FilterCell.tsx
> +  dataType: 'string'
```suggestion
  dataType: string
```

2024-11-28 21:42 UTC, SofiiaYevush approved these changes

2024-11-29 11:03 UTC, Made1ra approved these changes

2024-11-29 11:03 UTC, merged