Add a scrollbar to a signup form
ita-social-projects/SpaceToStudy-Client pull request #276
Opened 2022-08-26 07:52 UTC by dmytruk-y

A scrollbar added to a sign up form 

![image](https://user-images.githubusercontent.com/86732805/186850528-09896292-b5c9-40e8-b269-5a74868015bb.png)

2022-08-26 12:59 UTC, rostyslaw27 approved these changes

2022-08-27 09:49 UTC, maarekua requested changes

2022-08-27 09:49 UTC, maarekua commented on src/containers/guest-home-page/signup-dialog/signup-dialog.style.js
> +    padding: { xs: '30px 0 0 0', sm: '10px 20px 40px 80px', md: '10px 15px 0 75px' },
Fix design issues scroll should be aligned on board.

2022-08-31 09:32 UTC, High-Voltaged approved these changes

2022-09-02 09:16 UTC, maarekua approved these changes

2022-09-02 10:04 UTC, merged