Fixed changing a user photo in the header
ita-social-projects/SpaceToStudy-Client pull request #2812
Opened 2024-11-20 15:08 UTC by Made1ra

Before:

[![image](https://github.com/user-attachments/assets/89e15007-008c-437c-9574-9749c4e3176c)](https://private-user-images.githubusercontent.com/123400767/367610790-2b1cbff9-6067-479b-9d4a-f0a63ced2025.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTE4NDgsIm5iZiI6MTczMjExMTU0OCwicGF0aCI6Ii8xMjM0MDA3NjcvMzY3NjEwNzkwLTJiMWNiZmY5LTYwNjctNDc5Yi05ZDRhLWYwYTYzY2VkMjAyNS5tb3Y_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxNDA1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGQyMWYwOGFmOGYwMjhjMDczNTVkMzc5OTA2NDkwNWZhNTdjMWI2Mjk1Mjk2NzRkODhlNGVjNTUwMGE4ZmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l2WLcqjQ4F-9JL-iCcIThtYIEubXHu6k1R6D4XJ26OI)

After:

https://github.com/user-attachments/assets/1bc861d9-11d1-4049-b3a7-cef0e87e9a26

2024-11-20 15:44 UTC, ut5tw commented on src/containers/navigation-icons/AccountIcon.tsx
> +    if (statePhoto && statePhoto.src) {
replace `statePhoto && statePhoto.src` with `statePhoto?.src` so it's more concise and easier to read

2024-11-20 16:10 UTC, ut5tw approved these changes

2024-11-20 21:37 UTC, Renatavl requested changes

2024-11-20 21:37 UTC, Renatavl commented on src/containers/navigation-icons/AccountIcon.tsx
> +  const avatarSrc = getAvatarSrc()
The final result of this code is just a variable, that's why it is better to use `useMemo()` instead of `useCallback()`

2024-11-21 21:36 UTC, Renatavl approved these changes

2024-11-22 17:15 UTC, luiqor approved these changes

2024-11-22 17:44 UTC, merged