Feature/2705/create input field component
ita-social-projects/SpaceToStudy-Client pull request #2840
Opened 2024-11-21 21:09 UTC by PavloButynets

Implemented a reusable InputField component that meets the standards of the design system. This component will be used throughout the application to maintain consistency in input field styles, behavior, and accessibility. Added it to the storybook, wrote tests for it
https://youtu.be/rINxNyt-b8E

2024-11-22 13:35 UTC, amoutens requested changes

2024-11-22 13:35 UTC, amoutens commented on src/design-system/components/input-field/InputField.scss
> +  input::placeholder {
you can add this opacity setting to 133 line

2024-11-26 10:24 UTC, amoutens approved these changes

2024-11-26 10:47 UTC, Mav-Ivan commented
teammate that add comment should resolve it 
![image](https://github.com/user-attachments/assets/60575537-be2d-43a0-9c3b-02470c539332)

2024-11-26 10:47 UTC, Mav-Ivan approved these changes

2024-11-28 13:13 UTC, SofiiaYevush approved these changes

2024-11-28 13:22 UTC, ShadowOfTheSpace requested changes

2024-11-28 13:22 UTC, ShadowOfTheSpace commented on src/design-system/components/input-field/InputField.tsx
> +        } ${error ? 's2s-input-container_error' : ''}`}
Use `cn` function here

2024-11-28 13:22 UTC, ShadowOfTheSpace commented on src/design-system/components/input-field/InputField.tsx
> +        <div className={`s2s-helper-text-container`}>
```suggestion
        <div className='s2s-helper-text-container'>
```

2024-11-28 13:22 UTC, ShadowOfTheSpace commented on src/design-system/components/input-field/InputField.tsx
> +          <span className={error ? 's2s-helper-text-error' : 's2s-helper-text'}>
Use `cn` function here

2024-11-28 23:18 UTC, ShadowOfTheSpace commented on src/design-system/components/input-field/InputField.tsx
> +        })}
I think using `cn` this way (without object) will be more readable and simple, but it's up to you
```suggestion
        className={cn('s2s-input-container', 
        `s2s-input-container_${variant}`,
        disabled && 's2s-input-container_disabled',
        error && 's2s-input-container_error'
        )}
```

2024-11-28 23:18 UTC, ShadowOfTheSpace commented on src/design-system/components/input-field/InputField.tsx
> +            })}
Same here
I think that you should use object in `cn` function when your classname has the same name as condition. For example - classname = "error" and condition = error, so technically object is better for this example. But right now you have different names for classname and condition, and there is no reason to use object here.
But as I sad before, it's up to you)

2024-11-28 23:19 UTC, ShadowOfTheSpace approved these changes

2024-11-29 09:46 UTC, merged