Create CheckBox component for design system
ita-social-projects/SpaceToStudy-Client pull request #2841
Opened 2024-11-21 21:42 UTC by nebby2105

#2702 
Created Checkbox component with the following configurable props:

1.  color (primary, secondary, success, error)
2.  variant (check, middle)
3.  label
4.  labelPosition (top, bottom, end)
5.  size (sm, md, lg)
6.  loading
7.  disabled

Default Parameters:

Color: primary
Variant: check
Size: md
Label Position: end
Loading: false
Disabled: false

Default parameters:
<img width="209" alt="Screenshot 2024-11-21 at 18 17 49" src="https://github.com/user-attachments/assets/18f74ee4-c8d1-4e66-b8b3-154a17bd6475">

Color="success"
<img width="210" alt="Screenshot 2024-11-21 at 18 16 50" src="https://github.com/user-attachments/assets/6b924a66-59b0-46bb-ab7a-daf2bc0e329f">

Color="error"
<img width="214" alt="Screenshot 2024-11-21 at 18 17 04" src="https://github.com/user-attachments/assets/ee55827b-fa94-40f4-91dc-bfb147852b5d">

labelPosition="top"
<img width="184" alt="Screenshot 2024-11-21 at 18 17 19" src="https://github.com/user-attachments/assets/4364cd0b-8096-4326-9b02-e3cec7c0d9e8">

labelPosition="bottom"
<img width="202" alt="Screenshot 2024-11-21 at 18 17 32" src="https://github.com/user-attachments/assets/07e47f2c-90e1-495f-8d29-d213e09a77e9">

- [ ] create CheckBox component 
- [ ] add it to storybook
- [ ]  cover with tests

2024-11-22 11:29 UTC, amoutens requested changes

2024-11-22 11:29 UTC, amoutens commented on src/design-system/components/checkbox/CheckBox.tsx
> +interface CheckBoxProps extends Omit<CheckboxProps, 'size'> {
it is better to rename the interface due to the fact that the name coincides with the MUI props

2024-11-22 11:29 UTC, amoutens commented on src/design-system/components/checkbox/CheckBox.tsx
> +      <span className='s2s-checkbox__label'>{label}</span>
maybe it is better to use FormControlLabel from MUI

2024-11-22 11:32 UTC, amoutens requested changes

2024-11-22 11:32 UTC, amoutens commented on src/design-system/components/checkbox/CheckBox.tsx
> +  const loaderSize = size === 'sm' ? 14 : size === 'md' ? 18 : 20
Extract this nested ternary operation into an independent statement.

Fix this small sonar issue

2024-11-22 11:48 UTC, Made1ra requested changes

2024-11-22 11:48 UTC, Made1ra commented on src/design-system/components/checkbox/CheckBox.tsx
> +  const loaderSize = size === 'sm' ? 14 : size === 'md' ? 18 : 20
Extract this nested ternary operation `size === 'md' ? 18 : 20` into an independent statement for better code readability.

2024-11-22 11:48 UTC, Made1ra commented on src/design-system/stories/CheckBox.stories.tsx
> +import CheckBox from '../components/checkbox/CheckBox'
Consider using an absolute import for better readability and maintainability.

2024-11-22 18:28 UTC, amoutens approved these changes

2024-11-23 08:56 UTC, Made1ra approved these changes

2024-11-27 15:02 UTC, ShadowOfTheSpace requested changes

2024-11-27 15:02 UTC, ShadowOfTheSpace commented on src/design-system/components/checkbox/CheckBox.tsx
> +  const blockModifiers = [
Use `cn` function here, please
Look [here](https://github.com/ita-social-projects/SpaceToStudy-Client/blob/develop/src/design-system/components/button/Button.tsx#L67) for example

2024-11-27 15:36 UTC, ShadowOfTheSpace approved these changes

2024-11-27 19:01 UTC, Mav-Ivan commented on src/design-system/components/checkbox/CheckBox.tsx
> +interface S2SCheckBoxProps extends Omit<CheckboxProps, 'size'> {
Change S2SCheckBoxProps just to CheckBoxProps

2024-11-27 19:01 UTC, Mav-Ivan approved these changes

2024-11-28 19:57 UTC, merged