Created RadioButton component
ita-social-projects/SpaceToStudy-Client pull request #2842
Opened 2024-11-21 22:02 UTC by SofiiaYevush

Created RadioButton component that meets the design system standards.

Examples of RadioButton in Storybook:
![image](https://github.com/user-attachments/assets/0e41f42f-ef8a-42d0-9ef2-bb1336a6c8c8)

![image](https://github.com/user-attachments/assets/ad8200a3-3f39-42ba-9ac5-426aded0c7ce)

![image](https://github.com/user-attachments/assets/3cb7f410-335a-43f9-9d32-98bc94eb36bd)
[ img1, img2, img3: Relevant size, color, label position, checked:true ]

![image](https://github.com/user-attachments/assets/6668caba-2379-480b-ac72-2db95e31f9af)
[ img4: checked:false ]

![image](https://github.com/user-attachments/assets/e45c4e2a-e7fd-42bb-bd16-67c076e40f1b)
[ img5: disabled:true ]

![image](https://github.com/user-attachments/assets/8ca1aa89-397d-426d-9f19-56e8d8985698)
[ img6: loading:true ]

2024-11-22 01:26 UTC, ShadowOfTheSpace approved these changes

2024-11-26 10:49 UTC, Mav-Ivan requested changes
move component to src/design-system/components
move stories to src/design-system/stories
move test to tests/unit/design-system
Also use aliases `~scss-components `, `~scss`

2024-11-26 19:07 UTC, SofiiaYevush commented
> move component to src/design-system/components move stories to src/design-system/stories move test to tests/unit/design-system Also use aliases `~scss-components `, `~scss`

Done. 
Moved: `RadioButton.tsx, RadioButton.scss` to `src/design-system/components/radio-button`;
`RadioButton.stories.tsx` to `src/design-system/stories`;
`RadioButton.spec.jsx` to `tests/unit/design-system/components/radio-button`.
Added `~scss-components `, `~scss`.

2024-11-27 19:05 UTC, Mav-Ivan commented on src/design-system/components/radio-button/RadioButton.tsx
> +    const loader = loading ? (
add loading && (...

2024-11-27 19:06 UTC, Mav-Ivan approved these changes

2024-11-28 12:00 UTC, SofiiaYevush commented on src/design-system/components/radio-button/RadioButton.tsx
> +    const loader = loading ? (
> add loading && (...

Done. Changed logic for using loading.

2024-11-28 13:56 UTC, amoutens approved these changes

2024-11-28 14:20 UTC, merged