Fix tutor homepage schedule localization
ita-social-projects/SpaceToStudy-Client pull request #2847
Opened 2024-11-22 11:42 UTC by sandrvvu

**Problem:** The schedule block on the Tutor homepage is not displaying text in Ukrainian, even though the user's interface language is set to Ukrainian.
![image](https://github.com/user-attachments/assets/e0c286f8-3b7e-4d5d-8418-258245cd39a0)

**Result:**
(UA)
![image](https://github.com/user-attachments/assets/01cc2434-76ec-491a-a4d9-76edd46b3689)
(EN)
![image](https://github.com/user-attachments/assets/7c02c237-8a2b-41c5-9134-f8d2bf46a408)

2024-11-22 11:59 UTC, Made1ra requested changes

2024-11-22 11:59 UTC, Made1ra commented on src/components/tutor-schedule/TutorSchedule.tsx
> +        {t('tutorHomePage.schedule.AllClasses')}
I think it's better to use lower camel case here.
E.g. `allClasses` instead of `AllClasses`.

2024-11-22 12:10 UTC, sandrvvu commented on src/components/tutor-schedule/TutorSchedule.tsx
> +        {t('tutorHomePage.schedule.AllClasses')}
oh right, my bad)

2024-11-22 12:14 UTC, Made1ra approved these changes

2024-11-25 20:50 UTC, dudchakk requested changes
probably the price and date should be translated as well)
in this example it's `80 UAH/hour` and `18:00-19:30 Thu`

2024-11-27 21:27 UTC, Renatavl approved these changes

2024-12-01 16:05 UTC, Made1ra approved these changes

2024-12-02 13:38 UTC, markgol777 approved these changes

2024-12-02 13:55 UTC, dudchakk approved these changes

2024-12-02 13:56 UTC, merged