Created Alert component aligned with design system
ita-social-projects/SpaceToStudy-Client pull request #2895
Opened 2024-11-26 19:14 UTC by Made1ra

#### Description:
Implemented a reusable `Alert` component that meets the design system standards. This component will be used throughout the application to maintain consistency in alert styles, behavior, and accessibility.

[Figma](https://www.figma.com/design/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=21761-14630&t=Jdf03mGz0apvrAKS-4)

#### Requirements:
- **Styles:**
  - Follow design system variables for colors, typography, padding, and other styles.
  - Ensure hover, focus, active, and disabled states are defined according to the design system.
  - Provide a title for the alert.
  
- **Props:**
  - `variant`: Defines type (filled, outlined).
  - `label`: Provide a label for the Alert.
  -  `title `: Provide a title for the Alert.
  - `description`: Provide a description for the Alert.
  - `severity `: Representing different states (success, info, error, warning).
  -  `icon`: Optional prop, have the icon to each `severity` by default

<img width="1031" alt="Screenshot 2024-11-26 at 21 12 35" src="https://github.com/user-attachments/assets/6a72637e-3b66-4aa1-a7d5-850b0a4e1fbd">

<img width="1031" alt="Screenshot 2024-11-26 at 21 12 04" src="https://github.com/user-attachments/assets/241ed6be-1fee-40cd-93d4-614d32845836">

2024-11-27 09:52 UTC, amoutens commented on src/design-system/components/alert/Alert.tsx
> +          success: <CheckCircleOutline fontSize='inherit' />
maybe it is better to define this object outside the component

2024-11-27 10:24 UTC, amoutens approved these changes

2024-11-27 21:20 UTC, Renatavl approved these changes

2024-11-27 23:51 UTC, ShadowOfTheSpace commented on src/design-system/components/alert/Alert.tsx
> +const Alert = forwardRef(
I think it is better to use generic in `forwardRef` function. You will not have to type props and forwardedRef manually.

2024-11-28 09:24 UTC, ShadowOfTheSpace requested changes

2024-11-28 09:24 UTC, ShadowOfTheSpace commented on src/design-system/components/alert/Alert.tsx
> +    }: AlertProps,
```suggestion
    },
```
It is already typed by generic forwardRef

2024-11-28 09:28 UTC, ShadowOfTheSpace approved these changes

2024-11-28 09:29 UTC, merged