Implement AddReviewModal
ita-social-projects/SpaceToStudy-Client pull request #2915
Opened 2024-11-30 14:46 UTC by dudchakk

**Description:** This PR implements the design and functionality of the `Add review modal`, allowing users to leave feedback after a collaboration.

**!! Important:** For testing purposes, for now the modal opens when clicking on the `Close cooperation` button. After the functional will be finished, the modal will open after the user confirmes that he wants to close the cooperation.

### UI part:
- Developed the UI and layout of the modal based on the design specifications;
- Added controlled inputs for rating and review fields;
- Implemented conditional descriptions for students and tutors;
- Included Ukrainian translations for all text.

**How it looks:**

![image](https://github.com/user-attachments/assets/b0525ac4-791d-467a-8f3e-f41972334047)

2024-12-11 13:12 UTC, ShadowOfTheSpace requested changes

2024-12-11 13:12 UTC, ShadowOfTheSpace commented on src/containers/my-cooperations/add-review-modal/AddReviewModal.constants.ts
> +  targetUserRole: 'student' as UserRoleEnum.Student,
```suggestion
  targetUserRole: UserRoleEnum.Student,

```

2024-12-11 13:12 UTC, ShadowOfTheSpace commented on src/containers/my-cooperations/add-review-modal/AddReviewModal.styles.ts
> +  root: { p: 5 },
Move `root` styles to the top of styles since it's a top tree container

2024-12-11 13:12 UTC, ShadowOfTheSpace commented on src/containers/my-cooperations/add-review-modal/AddReviewModal.tsx
> +import { FC } from 'react'
Don't import `FC` from react. Just write `React.FC`. It will be more readable

2024-12-11 13:12 UTC, ShadowOfTheSpace commented on src/containers/my-cooperations/add-review-modal/AddReviewModal.tsx
> +      comment: reviewData.comment,
You are using `reviewData` variable before its initialization. Move this function down

2024-12-11 13:12 UTC, ShadowOfTheSpace commented on src/containers/my-cooperations/add-review-modal/AddReviewModal.tsx
> +        <Button color='tonal' onClick={() => closeModal()}>
```suggestion
        <Button color='tonal' onClick={closeModal}>

```

2024-12-11 13:12 UTC, ShadowOfTheSpace commented on src/containers/my-cooperations/cooperation-completion/CooperationCompletion.tsx
> +import { FC } from 'react'
Same here, please

2024-12-11 13:12 UTC, ShadowOfTheSpace commented on src/containers/my-cooperations/cooperation-completion/CooperationCompletion.tsx
> +  const openAddReviewModal = () => {
```suggestion
  const handleCloseCooperationButtonClick = () => {
```

2024-12-11 13:12 UTC, ShadowOfTheSpace commented on src/constants/translations/en/cooperations-page.json
> +    "success": "Your review was submitted seccessfully"
Where is a translation for `success` in ukrainian?

2024-12-11 13:30 UTC, dudchakk commented on src/containers/my-cooperations/add-review-modal/AddReviewModal.tsx
> +      comment: reviewData.comment,
in this case, the function is initialized before we're passing it to the useForm hook, which is right below. this is why this function needs to be declared here

2024-12-11 13:34 UTC, dudchakk commented on src/containers/my-cooperations/cooperation-completion/CooperationCompletion.tsx
> +  const openAddReviewModal = () => {
this modal will not open when we click on 'Close cooperation', it's for testing purposes. after we'll complete the cooperation closing process, I will change where this modal opens. so this name is not relatable

2024-12-11 13:44 UTC, ShadowOfTheSpace approved these changes

2025-02-05 14:30 UTC, luiqor commented on src/services/review-service.ts
> +}
TODO: replace with baseService

2025-02-05 14:30 UTC, luiqor commented on src/containers/my-cooperations/add-review-modal/AddReviewModal.tsx
> +
TODO: Should we add useMutation here ?

2025-02-05 14:30 UTC, luiqor commented on src/containers/my-cooperations/cooperation-completion/CooperationCompletion.tsx
TODO: Connect this logic with closing banners when user clocks "Accept" in cooperation closure. Other user will also need to recieve modal to leave review

2025-05-03 12:18 UTC, closed without merging