Bug fix
ita-social-projects/SpaceToStudy-Client pull request #2916
Opened 2024-11-30 14:59 UTC by PavloButynets

Fixed the styles, rewrote the component based on InputBase with MUI, added some props

2024-12-01 17:44 UTC, ShadowOfTheSpace approved these changes

2024-12-01 17:45 UTC, amoutens requested changes

2024-12-01 17:45 UTC, amoutens commented on src/design-system/components/input-field/InputField.scss
> +  .s2s-input-field {
better change to #{$prefix} from scss/utilities

2024-12-01 17:45 UTC, amoutens commented on src/design-system/components/input-field/InputField.tsx
> +  variant?: InputFieldVariantEnum
If you don`t change enum dist, please make pull for this branch. I replaced your enum to constants.ts

2024-12-02 09:08 UTC, amoutens approved these changes

2024-12-02 10:07 UTC, Made1ra commented on src/design-system/stories/InputField.stories.tsx
> +  }
Consider adding a space between event handlers.
```suggestion
  }
  
```

2024-12-02 11:01 UTC, nebby2105 approved these changes

2024-12-02 11:30 UTC, merged