Fixed invalid additionalInfo validation in enroll offer modal
ita-social-projects/SpaceToStudy-Client pull request #2918
Opened 2024-12-01 11:48 UTC by VKormylo

Added validation for additional info to be at least 30 symbols or empty in enroll offer modal.
Validation looks like this.
![image](https://github.com/user-attachments/assets/62456d7a-ebf3-4134-b65f-9f278af2627b)
If the field is empty, there is no validation.
![image](https://github.com/user-attachments/assets/f1010635-6c0b-4f7d-8ba7-2a1b79cf4978)

2024-12-01 12:25 UTC, markgol777 approved these changes

2024-12-01 12:25 UTC, markgol777 commented on src/components/app-text-area/AppTextArea.tsx
suggestion: Maybe put the ternary into a separate variable for better code reading

2024-12-01 12:26 UTC, markgol777 requested changes

2024-12-01 12:26 UTC, markgol777 commented on src/containers/offer-details/enroll-offer/EnrollOffer.styles.ts
It's not a good practise to use negative margins

2024-12-01 12:30 UTC, VKormylo commented on src/components/app-text-area/AppTextArea.tsx
Yes, I agree.

2024-12-01 12:30 UTC, VKormylo commented on src/containers/offer-details/enroll-offer/EnrollOffer.styles.ts
I'm going to fix that.

2024-12-01 12:57 UTC, VKormylo commented on src/containers/offer-details/enroll-offer/EnrollOffer.styles.ts
Fixed.

2024-12-03 11:09 UTC, markgol777 approved these changes

2024-12-03 17:27 UTC, luiqor reviewed
Additional info cannot be empty "" (0 characters), as it causes a server error. It must either be not included to request or contain more than 30 characters. Please update the logic to ensure that additionalInfo is not sent if the input field is empty string.

![image](https://github.com/user-attachments/assets/0960d2c6-17d8-438f-a157-ceca648f40bc)
![image](https://github.com/user-attachments/assets/da2e17b3-e510-4495-bf62-cd04e90adb5f)

2024-12-03 18:52 UTC, VKormylo commented
Fixed incorrect empty additionalInfo in request

2024-12-03 19:01 UTC, luiqor approved these changes

2024-12-03 20:19 UTC, SofiiaYevush approved these changes

2024-12-03 20:24 UTC, merged