create badge component
ita-social-projects/SpaceToStudy-Client pull request #2919
Opened 2024-12-01 21:28 UTC by nebby2105

Created Badge component #2861

**Props:**

- `variant`: Determines the badge style (`sm` or `lg`).
- `color`: Supports `primary`, `success`, and `error` colors (default: `primary`).
- `isVisible`: Controls visibility of the badge (default: `true`).
- `badgeContent`: Numeric or textual content (applies to `lg `variant).
- `maxContent`: Specifies the maximum number to display, e.g., 99+ (default: `10`).
- `isZeroShown`: Toggles visibility of 0 content for the `lg` variant (default:`false`).

**Examples:**
- variant ='`lg`'
- badgeContent='`7`'
- rest props by default
<img width="59" alt="Screenshot 2024-12-01 at 23 05 40" src="https://github.com/user-attachments/assets/ba845327-c7d9-47c7-83f7-359b8d62aa49">

--------------------

- variant = '`sm`'
<img width="48" alt="Screenshot 2024-12-01 at 23 05 48" src="https://github.com/user-attachments/assets/30246eab-36fa-4673-aadb-2603f49f9baf">

--------------------

- color = '`success`'
<img width="51" alt="Screenshot 2024-12-01 at 23 05 52" src="https://github.com/user-attachments/assets/a71ae579-97ef-4490-ba6e-cf0699f3a4e8">

--------------------

- color='`error`'
<img width="49" alt="Screenshot 2024-12-01 at 23 06 04" src="https://github.com/user-attachments/assets/6d21210c-3881-4ff8-bce6-1f7af9b7041e">

--------------------

- variant ='`lg`'
- color ='`success`'
- maxContent ='`99`'
<img width="74" alt="Screenshot 2024-12-01 at 23 06 20" src="https://github.com/user-attachments/assets/044a24c7-3b88-40a7-9d75-747b6f3579c4">

--------------------

- variant ='`lg`'
- badgeContent='`7`'
- color = '`error`'
<img width="53" alt="Screenshot 2024-12-01 at 23 06 24" src="https://github.com/user-attachments/assets/86c69d86-6528-45b4-959a-a21912cb8f39">

--------------------

- variant ='`lg`'
- badgeContent='`0`'
- isZeroShown
<img width="66" alt="Screenshot 2024-12-01 at 23 06 39" src="https://github.com/user-attachments/assets/d808ee1f-8315-4f95-a9b5-6f1e2f3a13d5">

--------------------

- [x] Implemented Badge component.
- [x] Added prop types and default values.
- [x] Integrated component into Storybook with examples.
- [x] Verified rendering and behavior through unit tests.

2024-12-01 22:40 UTC, ShadowOfTheSpace requested changes

2024-12-01 22:40 UTC, ShadowOfTheSpace commented on src/design-system/components/badge/Badge.tsx
> +  showZero?: boolean
Name it as a boolean, please
```suggestion
  isZeroShown?: boolean
```

2024-12-01 22:40 UTC, ShadowOfTheSpace commented on src/design-system/components/badge/Badge.tsx
> +const Badge: FC<BadgeProps> = ({ children, ...props }) => {
Do not import FC from react, just use React.FC instead. It it more clean and readable
```suggestion
const Badge: React.FC<BadgeProps> = ({ children, ...props }) => {
```

2024-12-01 22:40 UTC, ShadowOfTheSpace commented on src/design-system/components/badge/Badge.tsx
> +  const displayBadge = (props.isVisible ?? true) ? props.badgeContent : 0
`isVisible` field is in both of your types (`SmallBadgeProps` and `LargeBadgeProps`). So you can make a destructurization of this field, like you did with `children`, and add a default value there.

2024-12-01 22:40 UTC, ShadowOfTheSpace commented on src/design-system/components/badge/Badge.tsx
> +      max={props.variant === 'lg' ? (props.maxContent ?? 10) : undefined}
Extract this expression into separate variabale, please, like you did with `badgeVariant`

2024-12-01 22:40 UTC, ShadowOfTheSpace commented on src/design-system/components/badge/Badge.tsx
> +  return (
Add a blank line before return statement.
It is a really good practice to do that, but unfortunately we don't have a linter for that :(

2024-12-01 22:40 UTC, ShadowOfTheSpace commented on src/design-system/components/badge/Badge.tsx
> +      color={props.color ?? 'primary'}
Same as with `isVisible`. Add default value with destructurization, please

2024-12-01 23:37 UTC, ShadowOfTheSpace requested changes
Just renaming)
You can keep names of variables like in props without any conflict. It would be much better and readable

2024-12-01 23:37 UTC, ShadowOfTheSpace commented on src/design-system/components/badge/Badge.tsx
> +  const maxShown =
```suggestion
  const isZeroShown =
```

2024-12-01 23:37 UTC, ShadowOfTheSpace commented on src/design-system/components/badge/Badge.tsx
> +  const maxContentShown =
```suggestion
  const maxContent =
```

2024-12-01 23:37 UTC, ShadowOfTheSpace commented on src/design-system/components/badge/Badge.tsx
> +  const displayBadge = isVisible ? props.badgeContent : 0
```suggestion
  const badgeContent = isVisible ? props.badgeContent : 0
```

2024-12-01 23:37 UTC, ShadowOfTheSpace commented on src/design-system/components/badge/Badge.tsx
> +  const badgeVariant = props.variant === 'sm' ? 'dot' : 'standard'
```suggestion
  const variant = props.variant === 'sm' ? 'dot' : 'standard'
```

2024-12-02 00:09 UTC, ShadowOfTheSpace approved these changes

2024-12-03 16:23 UTC, amoutens approved these changes

2024-12-04 11:56 UTC, SofiiaYevush approved these changes

2024-12-04 12:24 UTC, merged