Feature/2862/divider
ita-social-projects/SpaceToStudy-Client pull request #2925
Opened 2024-12-02 21:05 UTC by markgol777

![image](https://github.com/user-attachments/assets/c6ba11bf-3891-4c83-8621-f86fa8f6ec4a)
Added Divider and bunch of styles with it

Like:

- [X] Horizontal
- [X] Vertical
- [X] Ellipse 
- [X] A lot of styling options for the above

2024-12-02 21:15 UTC, nebby2105 commented on src/design-system/components/divider/Divider.scss
> +      background-color: #c8ccd0;
maybe add colors to variables file (? not sure)

2024-12-02 21:15 UTC, nebby2105 commented on src/design-system/components/divider/Divider.tsx
> +          sx={{
not sure if its needed but you can add a className here and move styles into your .scss file (optional)

2024-12-03 10:14 UTC, markgol777 commented on src/design-system/components/divider/Divider.scss
> +      background-color: #c8ccd0;
Yeah that's a good suggestion

2024-12-03 10:27 UTC, markgol777 commented on src/design-system/components/divider/Divider.tsx
> +          sx={{
I'd rather keep it in sx for better code readability

2024-12-03 10:35 UTC, nebby2105 approved these changes

2024-12-03 12:07 UTC, amoutens requested changes

2024-12-03 12:07 UTC, amoutens commented on src/design-system/components/divider/Divider.tsx
> +const size = ['small', 'big'] as const
maybe better to replace big to large

2024-12-03 12:07 UTC, amoutens commented on src/design-system/components/divider/Divider.scss
> +    &-big {
change to large

2024-12-03 12:23 UTC, amoutens approved these changes

2024-12-03 13:26 UTC, ShadowOfTheSpace requested changes

2024-12-03 13:26 UTC, ShadowOfTheSpace commented on src/design-system/components/divider/Divider.tsx
> +  const width = thickness === 'lg' ? '#9199A1' : '#C8CCD0'
```suggestion
  const borderColor = thickness === 'lg' ? '#9199A1' : '#C8CCD0'
```
Rename it, please. It is not width

2024-12-03 13:26 UTC, ShadowOfTheSpace commented on tests/unit/design-system/components/Divider/Divider.spec.jsx
> +      />
Replace double quotes here

2024-12-03 13:26 UTC, ShadowOfTheSpace commented on tests/unit/design-system/components/Divider/Divider.spec.jsx
> +      />
Same here

2024-12-03 13:26 UTC, ShadowOfTheSpace commented on tests/unit/design-system/components/Divider/Divider.spec.jsx
> +      />
Add vscode extentions "Stylelint" and "Esilint". You will see all errors from our linter in vscode and also you will have an ability to auto fix all errors

2024-12-03 13:26 UTC, ShadowOfTheSpace commented on tests/unit/design-system/components/Divider/Divider.spec.jsx
> +      />
Double quotes)

2024-12-03 13:26 UTC, ShadowOfTheSpace commented on tests/unit/design-system/components/Divider/Divider.spec.jsx
> +      />
Double quotes again)

2024-12-03 13:32 UTC, markgol777 commented on src/design-system/components/divider/Divider.tsx
> +  const width = thickness === 'lg' ? '#9199A1' : '#C8CCD0'
fair enough, my bad

2024-12-03 13:38 UTC, ShadowOfTheSpace approved these changes

2024-12-03 13:40 UTC, merged