Replaced Alert throughout the project
ita-social-projects/SpaceToStudy-Client pull request #2951
Opened 2024-12-10 10:57 UTC by Made1ra

Replaced Alert with the reusable component from a [design system]((https://www.figma.com/design/liJZDYhUnDP15Pi9bipDcv/Space2Study-(Students)?node-id=21761-14630&t=Jdf03mGz0apvrAKS-4)).
Also, I've changed the import order in related files to match our coding convention.

Before:
<img width="471" alt="Screenshot 2024-12-10 at 12 30 42" src="https://github.com/user-attachments/assets/6b8f03f6-327d-40bb-a5b8-c5eccd527f49">

After:
<img width="537" alt="Screenshot 2024-12-12 at 14 49 03" src="https://github.com/user-attachments/assets/f60197fe-11dd-450f-a036-7034fd4bacd0" />

2024-12-10 12:03 UTC, SofiiaYevush approved these changes

2024-12-12 12:58 UTC, markgol777 approved these changes

2024-12-17 13:52 UTC, ShadowOfTheSpace requested changes

2024-12-17 13:52 UTC, ShadowOfTheSpace commented on src/constants/index.ts
> +import { AlertColor } from '~/design-system/components/alert/Alert'
Import it as a type
```suggestion
import { type AlertColor } from '~/design-system/components/alert/Alert'
```

2024-12-17 13:52 UTC, ShadowOfTheSpace commented on src/design-system/components/alert/Alert.tsx
> +          <p className={cn('s2s-alert-description')}>{description}</p>
```suggestion
          <p className='s2s-alert-description'>{description}</p>
```

2024-12-17 13:52 UTC, ShadowOfTheSpace commented on src/redux/features/snackbarSlice.ts
> +import { AlertColor } from '~/design-system/components/alert/Alert'
```suggestion
import { type AlertColor } from '~/design-system/components/alert/Alert'
```

2024-12-17 14:16 UTC, ShadowOfTheSpace approved these changes

2024-12-17 14:17 UTC, merged