Fix sonar issues
ita-social-projects/SpaceToStudy-Client pull request #2968
Opened 2024-12-12 10:28 UTC by sandrvvu

Fixed some sonar issues in pages, containers, components folder.

2024-12-12 13:13 UTC, amoutens approved these changes

2024-12-12 18:17 UTC, ShadowOfTheSpace requested changes

2024-12-12 18:17 UTC, ShadowOfTheSpace commented on src/components/message/Message.styles.ts
> +      backgroundColor = `basic.${isMyMessage ? 'turquoiseDark' : 'turquoiseChat'}`
I would recommend you extract the inner ternary operator to separate variable, and don't use `let` here because It decreases readability.

So you will have:
`const basicShade = isMyMessage ? 'turquoiseDark' : 'turquoiseChat'` and the same for `primary` one.
It will help you avoid nested conditions and conditions in string literals.

2024-12-12 18:17 UTC, ShadowOfTheSpace commented on src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
> +          option?.trim() ? option : t('common.languages.allLanguages')
Extract this to separate variable, please

2024-12-12 18:17 UTC, ShadowOfTheSpace commented on src/containers/my-cooperations/my-cooperations-details/MyCooperationsDetails.tsx
> +    <Box key={item} sx={style.languageItem}>
Are you sure that using item as a key is safe?

2024-12-12 18:17 UTC, ShadowOfTheSpace commented on src/pages/find-offers/FindOffers.tsx
> +        {renderOffersContent()}
Why do you need to call a function to get a static value? Use `useMemo` here for calculating the result and display it just like that `{offersContent}`

2024-12-16 14:59 UTC, Made1ra approved these changes

2024-12-16 14:59 UTC, Made1ra commented on src/containers/find-offer/offer-filter-block/offer-filter-list/OfferFilterList.tsx
> +  const getOptionLabelForLanguage = (option: LanguageFilter | null): string => {
```suggestion
  const getOptionLabelForLanguage = (option: LanguageFilter | null) => {
```
Is a return type here necessary?

2024-12-30 17:21 UTC, VKormylo approved these changes

2024-12-31 00:20 UTC, ShadowOfTheSpace approved these changes

2025-01-07 11:28 UTC, merged