made checkbox controllable
ita-social-projects/SpaceToStudy-Client pull request #2974
Opened 2024-12-12 21:38 UTC by nebby2105

2024-12-13 05:48 UTC, ShadowOfTheSpace requested changes

2024-12-13 05:48 UTC, ShadowOfTheSpace commented on src/design-system/components/checkbox/CheckBox.tsx
> +    event: React.ChangeEvent<HTMLInputElement>,
We don't need to pass this event to the `onChange` callback

2024-12-13 05:48 UTC, ShadowOfTheSpace commented on src/design-system/components/checkbox/CheckBox.tsx
> +  const [internalChecked, setInternalChecked] = useState<boolean>(false)
Add `defaultIsChecked` prop and use it here. And also rename state to `internalIsChecked`, please
```suggestion
  const [internalChecked, setInternalChecked] = useState<boolean>(defaultIsChecked ?? false)
```

2024-12-13 05:48 UTC, ShadowOfTheSpace commented on src/design-system/components/checkbox/CheckBox.tsx
> +  checked,
`checked` is a boolean, so rename it to `isChecked`. But also, to be more consistent in naming in this component, you should use rename while destructuring.
So you will have:
```isChecked: externalIsChecked```

2024-12-13 05:48 UTC, ShadowOfTheSpace commented on src/design-system/components/checkbox/CheckBox.tsx
> +    const newChecked = event.target.checked
We don't need event in `onChange` callback, so you can use destructurization here or even in function declaration, like `{ target: { checked } } : React.ChangeEvent<HTMLInputElement>)`

2024-12-13 05:48 UTC, ShadowOfTheSpace commented on src/design-system/components/checkbox/CheckBox.tsx
> +  const resolvedCheck = isCheckboxControllable ? checked : internalChecked
```suggestion
  const resolvedIsChecked = isCheckboxControllable ? externalIsChecked: internalIsChecked
```

2024-12-13 05:48 UTC, ShadowOfTheSpace commented on src/design-system/components/checkbox/CheckBox.tsx
> +          checked={resolvedCheck}
```suggestion
          checked={resolvedIsChecked}
```

2024-12-14 15:55 UTC, ShadowOfTheSpace requested changes

2024-12-14 15:55 UTC, ShadowOfTheSpace commented on src/design-system/components/checkbox/CheckBox.tsx
> +import { type ChangeEvent, ReactNode, useCallback, useState } from 'react'
```suggestion
import { type ChangeEvent, type ReactNode, useCallback, useState } from 'react'
```

2024-12-14 20:58 UTC, ShadowOfTheSpace approved these changes

2024-12-14 20:58 UTC, ShadowOfTheSpace commented on src/design-system/components/checkbox/CheckBox.tsx
> +    defaultChecked ?? false
You already assigned default value to the `defaultChecked` prop

2024-12-15 09:21 UTC, luiqor approved these changes

2024-12-15 14:19 UTC, markgol777 approved these changes

2024-12-16 14:30 UTC, merged