Added redirect to chat
ita-social-projects/SpaceToStudy-Client pull request #2998
Opened 2024-12-18 22:51 UTC by Renatavl

![image](https://github.com/user-attachments/assets/66658fd2-57ea-412d-8b4a-eea468d34cbc)

2024-12-19 15:02 UTC, ShadowOfTheSpace requested changes

2024-12-19 15:02 UTC, ShadowOfTheSpace commented on src/containers/user-profile/profile-info/ProfileInfo.tsx
> +  const getChats = useCallback(() => chatService.getChats(), [])
You can pass just `chatService.getChats` to `service` prop of `useAxios` hook

2024-12-19 15:02 UTC, ShadowOfTheSpace commented on src/containers/user-profile/profile-info/ProfileInfo.tsx
> +  } = useAxios({
Add generic type to the `useAxios` hook, and you will not have that weird types assertions in finding existing chat, because right now `listOfChats` has `never` type
```suggestion
  } = useAxios<ChatResponse[]>({
```

2024-12-19 15:02 UTC, ShadowOfTheSpace commented on src/containers/user-profile/profile-info/ProfileInfo.tsx
> +      chatId: existedChat?._id || '',
```suggestion
      chatId: existedChat?._id ?? '',
```

2024-12-19 15:02 UTC, ShadowOfTheSpace commented on src/containers/user-profile/profile-info/ProfileInfo.tsx
> +    const existedChat = listOfChats.find((chat: ChatResponse) =>
Add curly braces to this function, because it doesn't fit into a single line

2024-12-27 22:14 UTC, ShadowOfTheSpace requested changes

2024-12-27 22:14 UTC, ShadowOfTheSpace commented on src/containers/user-profile/profile-info/ProfileInfo.tsx
> +    service: () => chatService.getChats(),
You can pass reference for this service function directly without additional function
```suggestion
    service: chatService.getChats,
```

2024-12-27 22:14 UTC, ShadowOfTheSpace commented on src/containers/user-profile/profile-info/ProfileInfo.tsx
> +    defaultResponse: []
use `defaultResponses.array` from `src\constants\index.ts`

2024-12-27 22:14 UTC, ShadowOfTheSpace commented on src/containers/user-profile/profile-info/ProfileInfo.tsx
> +    const existedChat = listOfChats.find((chat: ChatResponse) => {
Chat already typed automatically here

```suggestion
    const existedChat = listOfChats.find((chat) => {
```

2025-01-14 09:40 UTC, Renatavl commented on src/containers/user-profile/profile-info/ProfileInfo.tsx
> +    service: () => chatService.getChats(),
@ShadowOfTheSpace, it will not work because of typescript. Everywhere in the project it is written like this (either through a separate function like `getChats ` which was removed with the last comments, or through an arrow function).

So `()=>` is required here.

2025-01-14 17:03 UTC, ShadowOfTheSpace approved these changes

2025-01-16 09:09 UTC, Mike-Popovych approved these changes

2025-01-29 12:43 UTC, luiqor approved these changes

2025-02-06 17:11 UTC, Mav-Ivan approved these changes

2025-02-06 17:11 UTC, merged