Replaced `useAxios` with `useQuery` on the My Cooperations Page
ita-social-projects/SpaceToStudy-Client pull request #3018
Opened 2024-12-21 10:16 UTC by Made1ra

Replaced the useAxios hook with a custom useQuery hook on the My Cooperations page to improve data fetching, caching, and error handling.

2024-12-31 12:39 UTC, markgol777 requested changes

2024-12-31 12:39 UTC, markgol777 commented on src/containers/my-cooperations/accept-cooperation-modal/AcceptCooperationModal.tsx
Do we not have a Coorperation interface to replace the unkown with?

2024-12-31 12:39 UTC, markgol777 commented on src/containers/my-cooperations/cooperations-container/CooperationContainer.tsx
same here

2024-12-31 12:39 UTC, markgol777 commented on src/pages/my-cooperations/MyCooperations.tsx
> -    service: getMyCooperations,
Why did you decide to remove the
getMyCoorperations function?
Also with the new PR you can finally use default response without any problems

2024-12-31 12:39 UTC, markgol777 commented on src/pages/my-cooperations/MyCooperations.tsx
> +            pageCount={data?.count ? Math.ceil(data.count / itemsPerPage) : 0}
Replace the 0 with a 1 as the page can't start with a 0 but I'm not sure on this one 😓

2025-01-01 15:41 UTC, markgol777 requested changes

2025-01-01 15:41 UTC, markgol777 commented on src/components/active-students/ActiveStudentsBlock.tsx
> +    data = defaultResponse,
We have intialData in our useQuery hook please don't use it this way

2025-01-01 15:41 UTC, markgol777 commented on src/pages/my-cooperations/MyCooperations.tsx
> +    data = defaultResponse,
Same thing here please use intialData in useQuery options

2025-01-01 15:41 UTC, markgol777 commented on src/pages/my-cooperations/MyCooperations.tsx
> +  } = useQuery<ItemsWithCount<Cooperation>>({
Also you don't have to specify the types anymore

2025-01-01 15:41 UTC, markgol777 commented on src/components/active-students/ActiveStudentsBlock.tsx
> +  } = useQuery<ItemsWithCount<Cooperation>>({
Also you don't have to specify the types anymore

2025-01-01 15:55 UTC, markgol777 requested changes

2025-01-01 15:55 UTC, markgol777 commented on src/components/active-students/ActiveStudentsBlock.tsx
> +  if (error) {
```js
 if (loading) return <Loader pageLoad size={50} />
  if (error) return null
  ```

Why did you change it from this to the ones with {}?

2025-01-01 15:56 UTC, Made1ra commented on src/components/active-students/ActiveStudentsBlock.tsx
> +  if (error) {
It's more readable.

2025-01-01 15:58 UTC, markgol777 approved these changes

2025-01-02 10:07 UTC, SofiiaYevush approved these changes

2025-01-02 11:31 UTC, ShadowOfTheSpace approved these changes

2025-01-02 11:44 UTC, merged