replaced useAxios hook with useQuery and fixed all the bugs with it
ita-social-projects/SpaceToStudy-Client pull request #3024
Opened 2024-12-24 13:01 UTC by markgol777

2024-12-26 22:05 UTC, ShadowOfTheSpace requested changes

2024-12-26 22:05 UTC, ShadowOfTheSpace commented on src/components/popular-categories/PopularCategories.tsx
> +  const oppositeRole = useMemo(() => getOpositeRole(userRole), [userRole])
You need to use the `useMemo` hook for some complex calculations that need to be stable across rerenders. `getOpositeRole` is just a ternary operator, so `useMemo` is too much for that. Overmemoization can be worth more than no memoization at all.

2024-12-26 22:05 UTC, ShadowOfTheSpace commented on src/components/popular-categories/PopularCategories.tsx
> +import { FC, useMemo, useCallback } from 'react'
Do not import `FC`, use `React.FC`, please

2024-12-26 22:05 UTC, ShadowOfTheSpace commented on src/components/popular-categories/PopularCategories.tsx
> +import { AxiosResponse } from 'axios'
```suggestion
import { type AxiosResponse } from 'axios'
```

2024-12-27 10:01 UTC, markgol777 commented on src/components/popular-categories/PopularCategories.tsx
> +  const oppositeRole = useMemo(() => getOpositeRole(userRole), [userRole])
You're right but since it was there before I started working on the component I just let it be

2024-12-27 10:16 UTC, markgol777 commented on src/components/popular-categories/PopularCategories.tsx
> +import { AxiosResponse } from 'axios'
sure

2024-12-27 11:07 UTC, Made1ra approved these changes

2025-01-01 10:49 UTC, markgol777 commented
Outdated

2025-01-01 10:49 UTC, closed without merging