Replaced useAxios with useQuery in ActiveStudentsBlock Component
ita-social-projects/SpaceToStudy-Client pull request #3036
Opened 2024-12-28 14:40 UTC by SofiiaYevush

Replaced `useAxios` with `useQuery` to manage data fetching using React Query in the ActiveStudentsBlock Component.

Relevant blocks:
![image](https://github.com/user-attachments/assets/6ef7e6cf-e70b-436b-892c-875a221aa6dd)

![image](https://github.com/user-attachments/assets/cb79d8a1-607c-44f8-8201-c32da997a5e5)

![image](https://github.com/user-attachments/assets/54c2e63b-bd33-4858-a12e-6ad0dccd927b)

**Issue:** #3012

2024-12-30 13:15 UTC, Made1ra approved these changes

2024-12-30 13:15 UTC, Made1ra commented on src/components/active-students/ActiveStudentsBlock.tsx
> +  if (isLoading) return <Loader pageLoad size={50} />
```suggestion
  if (isLoading) {
    return <Loader pageLoad size={50} />
  }
```

2024-12-30 13:15 UTC, Made1ra commented on src/components/active-students/ActiveStudentsBlock.tsx
> +  if (isError) return null
```suggestion
  if (isError) {
    return null
  }
```

2025-01-01 18:00 UTC, ShadowOfTheSpace requested changes

2025-01-01 18:00 UTC, ShadowOfTheSpace commented on src/components/active-students/ActiveStudentsBlock.tsx
> +  }
Please, use `baseSerivce` inside `getCooperation` function for correct typed function. You will not have to do `response.data` manually and cast it as `ItemsWithCount<Cooperation>`
```suggestion
  const fetchMyCooperations = () => {
    return cooperationService.getCooperations({
      limit: 3,
      status: 'active'
    })
  }
```

2025-01-01 18:00 UTC, ShadowOfTheSpace commented on src/components/active-students/ActiveStudentsBlock.tsx
> +  } = useQuery<ItemsWithCount<Cooperation>, Error>({
```suggestion
  } = useQuery({
```
It will be typed automatically after using `baseService`

2025-01-01 18:00 UTC, ShadowOfTheSpace commented on src/components/active-students/ActiveStudentsBlock.tsx
> +    data = defaultResponse,
Instead of this, add `options: { initialData: defaultResponse }`
```suggestion
    data
```

2025-01-01 18:08 UTC, closed without merging