Replaced the chip component through out the whole project
ita-social-projects/SpaceToStudy-Client pull request #3044
Opened 2024-12-31 16:49 UTC by markgol777

![image](https://github.com/user-attachments/assets/d0a8b982-7cf9-42cb-8b17-7607f4008e5a)

![image](https://github.com/user-attachments/assets/5360171d-3fbf-405b-84ca-80ee5d9b87ef)

![image](https://github.com/user-attachments/assets/4e7110b9-1e07-470c-9a58-b87ae6c641fb)

Replaced Chip component + fixed the styles of it to represent the figma mockup better

TODO

- [ ] Add proper coloring to category chips (Backend changes needed)

2025-01-02 10:57 UTC, ShadowOfTheSpace requested changes

2025-01-02 10:57 UTC, ShadowOfTheSpace commented on src/components/subject-level-chips/SubjectLevelChips.tsx
> +        label={subject || ''}
```suggestion
        label={subject ?? ''}
```

2025-01-02 10:57 UTC, ShadowOfTheSpace commented on src/components/subject-level-chips/SubjectLevelChips.tsx
Remove comments from this file, please

2025-01-02 10:57 UTC, ShadowOfTheSpace commented on src/components/status-chip/StatusChip.styles.ts
> +import { type ChipColor } from '~scss-components/chip/types'
It is bad practice to import directly from an internal folder of the component.
You can use `ComponentProps<typeof Chip>` and `Exclude` utility type to exctract this type from the component props.
Or just add re-export of this type inside `Chip.tsx` file, it's up to you

2025-01-03 06:47 UTC, ShadowOfTheSpace approved these changes

2025-01-06 13:32 UTC, amoutens approved these changes

2025-01-10 17:14 UTC, SofiiaYevush approved these changes

2025-01-21 14:59 UTC, merged