splits routes.js into separate files
ita-social-projects/SpaceToStudy-Client pull request #309
Opened 2022-09-11 08:46 UTC by Pipuss

2022-09-14 10:49 UTC, maarekua requested changes

2022-09-14 10:49 UTC, maarekua commented on src/containers/guest-home-page/Welcome.js
> +const scrollTo = guestRoutes.guestNavBar.whatCanYouDo.path
guest-guest-guest?

2022-09-14 10:49 UTC, maarekua commented on src/containers/guest-home-page/google-login/GoogleLogin.js
> +  const { whatCanYouDo } = guestRoutes.guestNavBar
guest guest

2022-09-19 13:23 UTC, Pipuss commented on src/containers/guest-home-page/Welcome.js
> +const scrollTo = guestRoutes.guestNavBar.whatCanYouDo.path
good remark 
fixed

2022-09-21 08:43 UTC, closed without merging