login popup
ita-social-projects/SpaceToStudy-Client pull request #55
Opened 2022-05-13 19:41 UTC by tarasSanotskyi

2022-05-30 11:31 UTC, maarekua commented on src/containers/modal/Modal.js
> +      // fullScreen
// @TODO fullscreen

2022-05-30 21:17 UTC, tarasSanotskyi commented on src/containers/modal/Modal.js
> +      // fullScreen
fixed

2022-06-03 07:53 UTC, maarekua requested changes

2022-06-03 08:38 UTC, tarasSanotskyi commented on src/components/google-login/GoogleLogin.js
> +const GoogleLogin = () => {
fixed

2022-06-03 08:38 UTC, tarasSanotskyi commented on src/components/login-dialog/LoginDialog.js
> +const LoginDialog = () => {
fixed

2022-06-03 08:38 UTC, tarasSanotskyi commented on src/components/login-form/LoginForm.js
> +const LoginForm = ({ handleSubmit, handleChange, handleBlur, data, errors }) => {
fixed

2022-06-03 08:38 UTC, tarasSanotskyi commented on src/containers/login-dialog/LoginDialog.js
> +const LoginDialog = () => {
fixed

2022-06-03 16:06 UTC, merged