Feature/68/sidebar
ita-social-projects/SpaceToStudy-Client pull request #71
Opened 2022-06-05 21:03 UTC by tarasSanotskyi

Create sidebar component 
test sidebar 
refactor navbar
test navbar

2022-06-09 14:25 UTC, tarasSanotskyi commented on src/pages/guest-home-page/GuestHome.js
> +      <Box id='whatCanYouDo' sx={ { width: '100%', height: '100vh', backgroundColor: 'primary.600' } }  />
for functional testing
will be deleted

2022-06-16 08:33 UTC, maarekua requested changes

2022-06-16 08:33 UTC, maarekua commented on src/containers/navbar/NavBar.js
> +  const openSidebar = () => setIsOpen(true)
I suggest creating one method and passing neither you want to set it to true or false, or rename state ti isSideBarActive, setIsSidebarActive, and use directly setter without methods.

2022-06-16 08:33 UTC, maarekua commented on src/containers/sidebar/sidebar.style.js
> +    margin: '10px 10px 10px 261px'
margin 261?

2022-06-16 08:33 UTC, maarekua commented on tests/unit/hooks/use-hash-scroll.spec.js
> +jest.mock('react-router-dom', () => ({
https://testing-library.com/docs/example-react-router/

2022-06-17 08:19 UTC, maarekua requested changes

2022-06-22 07:43 UTC, maarekua approved these changes

2022-06-22 07:43 UTC, merged