Fixed title text “Share your experience” is shown in two lines in the tutor registration block.
ita-social-projects/SpaceToStudy-Client pull request #769
Opened 2023-05-26 18:22 UTC by TSlashDreamy

I'm not sure if i am even allowed to change any project styles, but i had 3 different options to resolve this problem:

1. Redusing title font-size
2. Redusing padding of InfoCards
3. Removing letter-spacing from title

So, i picked most neutral option and just removed letter-spacing from titles in InfoCards.

Before:
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/834b210a-e11b-4ffc-9986-cc18abd95b79)

After:
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/cf4c5977-c1da-4248-90a1-ea1b7bfbdf88)

2023-05-27 07:14 UTC, MickhaelSh approved these changes

2023-05-27 07:15 UTC, Tolik170 approved these changes

2023-05-27 19:46 UTC, tsivkadi approved these changes

2023-05-29 07:36 UTC, maarekua commented on src/components/info-card/InfoCard.styles.js
> +      letterSpacing: '0',
Is this letter spacing according to Figma design?

2023-05-29 13:19 UTC, TSlashDreamy commented on src/components/info-card/InfoCard.styles.js
> +      letterSpacing: '0',
There is nothing in the figma design about letter spacing, but I found differences in font size between the figma design and the result in development. Am I allowed to change it?

Figma:
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/a00999fb-1b54-4cd9-8ecf-db016afe5f98)

Production:
![зображення](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/45912519/c82d0953-0507-4e56-9ac9-8519ae5f3420)

2023-05-29 15:29 UTC, MickhaelSh commented on src/components/info-card/InfoCard.styles.js
> +      letterSpacing: '0',
yes, do according to figma

2023-05-29 16:58 UTC, MickhaelSh requested changes
do new pr without others` commits

2023-05-29 17:49 UTC, TSlashDreamy commented on src/components/info-card/InfoCard.styles.js
> +      letterSpacing: '0',
I resized the font-size according to Figma design. The sizes are the same for web, tablet and mobile (24px)

2023-05-29 17:50 UTC, TSlashDreamy commented
> do new pr without others` commits

Done it in this branch. Removed other commits and added just mine

2023-05-29 17:51 UTC, MickhaelSh approved these changes

2023-05-30 20:52 UTC, merged