disable closing window outside popup
ita-social-projects/SpaceToStudy-Client pull request #785
Opened 2023-05-29 19:40 UTC by DLmar

We needed to prevent window closing when we click outside our modal window. Now it's fixed

2023-05-30 06:34 UTC, Tolik170 requested changes

2023-05-30 06:34 UTC, Tolik170 commented on src/components/popup-dialog/PopupDialog.tsx
> +      onClick={(e) => e.stopPropagation()}
I guess, we should add leave confirmation when data is filled in the modal, not disable default behaviour

2023-05-31 09:21 UTC, Tolik170 approved these changes

2023-06-02 11:06 UTC, maarekua approved these changes

2023-06-03 06:37 UTC, merged