fixed the text under the button Sign Up with Google
ita-social-projects/SpaceToStudy-Client pull request #838
Opened 2023-06-06 12:17 UTC by Taras-Shavel

I changed the text from "Already have a tutor account? Login!" to "Already have a Space2Study account?" under the button Sign Up with Google
![Inkedimage](https://github.com/ita-social-projects/SpaceToStudy-Client/assets/121514132/1a9792a3-15f2-4e72-9870-994dd7dcb783)

2023-06-06 18:26 UTC, Yurenko requested changes

2023-06-06 18:26 UTC, Yurenko commented on .env.local
Don't push env file.

2023-06-14 18:31 UTC, tsivkadi approved these changes

2023-06-15 07:09 UTC, Taras-Shavel commented on .env.local
done

2023-06-15 07:19 UTC, Yurenko approved these changes

2023-06-15 07:22 UTC, merged