bug/91/fix position of close icon in popup
ita-social-projects/SpaceToStudy-Client pull request #92
Opened 2022-06-24 13:36 UTC by tarasSanotskyi

Fix position of close icon in PopupDialog component
Refactor PopupDialog for using useBreacpoints custom hook

2022-06-25 10:04 UTC, maarekua requested changes

2022-06-25 10:04 UTC, maarekua commented on src/components/popup-dialog/popup-dialog.style.js
> +    float: 'right',
remove float

2022-06-25 10:20 UTC, tarasSanotskyi commented on src/components/popup-dialog/popup-dialog.style.js
> +    float: 'right',
done

2022-06-27 09:19 UTC, rostyslaw27 approved these changes

2022-06-28 16:43 UTC, LubomyrKashuba approved these changes

2022-06-29 07:25 UTC, maarekua approved these changes

2022-06-29 07:26 UTC, merged